import { Service } from '@/types';
import gutterCleaningImg from '@/assets/gutter-cleaning.jpg';
import roofInspectionImg from '@/assets/roof-inspection.jpg';
import roofRepairImg from '@/assets/roof-repair.jpg';
import emergencyTarpImg from '@/assets/emergency-tarp.jpg';
import skylightResealImg from '@/assets/skylight-reseal.jpg';
import gutterGuardsImg from '@/assets/gutter-guards.jpg';
import roofTuneupImg from '@/assets/roof-tuneup.jpg';
import chimneyFlashingImg from '@/assets/chimney-flashing.jpg';
import ventilationImg from '@/assets/ventilation.jpg';
import downspoutExtensionImg from '@/assets/downspout-extension.jpg';

export const demoServices: Service[] = [
  {
    id: 'svc-1',
    slug: 'gutter-cleaning',
    category: 'gutters',
    title: 'Gutter Cleaning',
    description: 'Complete gutter cleaning with debris removal and downspout flushing. Protect your home from water damage.',
    heroImage: gutterCleaningImg,
    basePrice: 150,
    unit: 'linear_ft',
    durationMin: 120,
    inclusions: ['Debris removal', 'Downspout check', 'Minor unclogging', 'Gutter inspection'],
    exclusions: ['Gutter repair', 'Downspout replacement', 'Gutter guard installation'],
    addons: [
      { id: 'addon-1', title: 'Downspout Flush', price: 50, description: 'Deep clean all downspouts' },
      { id: 'addon-2', title: 'Debris Haul-Away', price: 35, description: 'Remove all debris from property' },
    ],
    applicableTo: 'both',
  },
  {
    id: 'svc-2',
    slug: 'roof-inspection',
    category: 'roofing',
    title: 'Roof Inspection',
    description: 'Comprehensive roof inspection with detailed report. Identify issues before they become costly repairs.',
    heroImage: roofInspectionImg,
    basePrice: 200,
    unit: 'fixed',
    durationMin: 90,
    inclusions: ['Visual inspection', 'Photo documentation', 'Written report', 'Repair recommendations'],
    exclusions: ['Repairs', 'Material replacement', 'Permit applications'],
    addons: [
      { id: 'addon-3', title: 'Drone Inspection', price: 100, description: 'Aerial photography and analysis' },
      { id: 'addon-4', title: 'Thermal Imaging', price: 150, description: 'Detect hidden moisture issues' },
    ],
    applicableTo: 'both',
  },
  {
    id: 'svc-3',
    slug: 'roof-repair-small',
    category: 'roofing',
    title: 'Small Roof Repair',
    description: 'Fix minor leaks, replace damaged shingles, and seal problem areas. Quick turnaround for urgent repairs.',
    heroImage: roofRepairImg,
    basePrice: 350,
    unit: 'sqft',
    durationMin: 180,
    inclusions: ['Leak identification', 'Shingle replacement (up to 10)', 'Flashing repair', '1-year warranty'],
    exclusions: ['Full roof replacement', 'Structural repairs', 'Permit fees'],
    addons: [
      { id: 'addon-5', title: 'Extended Warranty', price: 75, description: '3-year coverage on repairs' },
    ],
    applicableTo: 'both',
  },
  {
    id: 'svc-4',
    slug: 'emergency-tarp',
    category: 'storm',
    title: 'Emergency Roof Tarp',
    description: '24/7 emergency service to protect your home from storm damage. Fast response guaranteed.',
    heroImage: emergencyTarpImg,
    basePrice: 400,
    unit: 'fixed',
    durationMin: 120,
    inclusions: ['Emergency response', 'Heavy-duty tarp', 'Professional installation', 'Temporary protection'],
    exclusions: ['Permanent repairs', 'Insurance claims processing', 'Interior cleanup'],
    addons: [
      { id: 'addon-6', title: 'After-Hours Service', price: 150, description: 'Evening/weekend priority response' },
    ],
    applicableTo: 'both',
  },
  {
    id: 'svc-5',
    slug: 'skylight-reseal',
    category: 'maintenance',
    title: 'Skylight Resealing',
    description: 'Stop leaks around skylights with professional resealing. Prevent water damage and improve energy efficiency.',
    heroImage: skylightResealImg,
    basePrice: 275,
    unit: 'fixed',
    durationMin: 150,
    inclusions: ['Old sealant removal', 'Professional-grade sealant', 'Frame inspection', '2-year warranty'],
    exclusions: ['Skylight replacement', 'Frame repair', 'Interior painting'],
    addons: [],
    applicableTo: 'residential',
  },
  {
    id: 'svc-6',
    slug: 'gutter-guards',
    category: 'gutters',
    title: 'Gutter Guard Installation',
    description: 'Premium gutter protection system. Reduce maintenance and extend gutter life.',
    heroImage: gutterGuardsImg,
    basePrice: 12,
    unit: 'linear_ft',
    durationMin: 240,
    inclusions: ['Premium mesh guards', 'Professional installation', 'Gutter cleaning before install', '5-year warranty'],
    exclusions: ['Gutter replacement', 'Fascia repair', 'Downspout extensions'],
    addons: [
      { id: 'addon-7', title: 'Heated Gutter System', price: 500, description: 'Prevent ice dams and clogs' },
    ],
    applicableTo: 'both',
  },
  {
    id: 'svc-7',
    slug: 'roof-tune-up',
    category: 'maintenance',
    title: 'Roof Tune-Up',
    description: 'Annual maintenance package. Keep your roof in top condition and catch issues early.',
    heroImage: roofTuneupImg,
    basePrice: 225,
    unit: 'fixed',
    durationMin: 120,
    inclusions: ['Complete inspection', 'Minor repairs', 'Sealant touch-up', 'Gutter check', 'Photo report'],
    exclusions: ['Major repairs', 'Material replacement', 'Structural work'],
    addons: [],
    applicableTo: 'both',
  },
  {
    id: 'svc-8',
    slug: 'chimney-flashing',
    category: 'roofing',
    title: 'Chimney Flashing Repair',
    description: 'Fix or replace chimney flashing to prevent leaks. Common source of water damage.',
    heroImage: chimneyFlashingImg,
    basePrice: 425,
    unit: 'fixed',
    durationMin: 180,
    inclusions: ['Old flashing removal', 'New metal flashing', 'Professional sealing', '2-year warranty'],
    exclusions: ['Chimney repair', 'Masonry work', 'Cap replacement'],
    addons: [],
    applicableTo: 'residential',
  },
  {
    id: 'svc-9',
    slug: 'ventilation-upgrade',
    category: 'maintenance',
    title: 'Roof Ventilation Upgrade',
    description: 'Improve attic ventilation for better energy efficiency and roof longevity.',
    heroImage: ventilationImg,
    basePrice: 550,
    unit: 'fixed',
    durationMin: 240,
    inclusions: ['Ventilation assessment', 'Vent installation', 'Attic inspection', 'Energy efficiency report'],
    exclusions: ['Insulation work', 'Attic cleanup', 'Structural modifications'],
    addons: [
      { id: 'addon-8', title: 'Solar Attic Fan', price: 300, description: 'Energy-efficient ventilation' },
    ],
    applicableTo: 'both',
  },
  {
    id: 'svc-10',
    slug: 'downspout-extension',
    category: 'gutters',
    title: 'Downspout Extensions',
    description: 'Direct water away from foundation. Prevent basement flooding and foundation damage.',
    heroImage: downspoutExtensionImg,
    basePrice: 85,
    unit: 'linear_ft',
    durationMin: 90,
    inclusions: ['Extension pipe', 'Professional installation', 'Splash block', 'Grading assessment'],
    exclusions: ['Landscaping', 'French drains', 'Foundation waterproofing'],
    addons: [],
    applicableTo: 'both',
  },
];
