import { Service, User, Order, Promo, Notification } from '@/types';
import gutterCleaningImg from '@/assets/gutter-cleaning.jpg';
import roofInspectionImg from '@/assets/roof-inspection.jpg';
import roofRepairImg from '@/assets/roof-repair.jpg';
import emergencyTarpImg from '@/assets/emergency-tarp.jpg';
import skylightResealImg from '@/assets/skylight-reseal.jpg';
import gutterGuardsImg from '@/assets/gutter-guards.jpg';
import roofTuneupImg from '@/assets/roof-tuneup.jpg';
import chimneyFlashingImg from '@/assets/chimney-flashing.jpg';
import ventilationImg from '@/assets/ventilation.jpg';
import downspoutExtensionImg from '@/assets/downspout-extension.jpg';

export const demoServices: Service[] = [
  {
    id: 'svc-1',
    slug: 'gutter-cleaning',
    category: 'gutters',
    title: 'Gutter Cleaning',
    description: 'Complete gutter cleaning with debris removal and downspout flushing. Protect your home from water damage.',
    heroImage: gutterCleaningImg,
    basePrice: 150,
    unit: 'linear_ft',
    durationMin: 120,
    inclusions: ['Debris removal', 'Downspout check', 'Minor unclogging', 'Gutter inspection'],
    exclusions: ['Gutter repair', 'Downspout replacement', 'Gutter guard installation'],
    addons: [
      { id: 'addon-1', title: 'Downspout Flush', price: 50, description: 'Deep clean all downspouts' },
      { id: 'addon-2', title: 'Debris Haul-Away', price: 35, description: 'Remove all debris from property' },
    ],
  },
  {
    id: 'svc-2',
    slug: 'roof-inspection',
    category: 'roofing',
    title: 'Roof Inspection',
    description: 'Comprehensive roof inspection with detailed report. Identify issues before they become costly repairs.',
    heroImage: roofInspectionImg,
    basePrice: 200,
    unit: 'fixed',
    durationMin: 90,
    inclusions: ['Visual inspection', 'Photo documentation', 'Written report', 'Repair recommendations'],
    exclusions: ['Repairs', 'Material replacement', 'Permit applications'],
    addons: [
      { id: 'addon-3', title: 'Drone Inspection', price: 100, description: 'Aerial photography and analysis' },
      { id: 'addon-4', title: 'Thermal Imaging', price: 150, description: 'Detect hidden moisture issues' },
    ],
  },
  {
    id: 'svc-3',
    slug: 'roof-repair-small',
    category: 'roofing',
    title: 'Small Roof Repair',
    description: 'Fix minor leaks, replace damaged shingles, and seal problem areas. Quick turnaround for urgent repairs.',
    heroImage: roofRepairImg,
    basePrice: 350,
    unit: 'sqft',
    durationMin: 180,
    inclusions: ['Leak identification', 'Shingle replacement (up to 10)', 'Flashing repair', '1-year warranty'],
    exclusions: ['Full roof replacement', 'Structural repairs', 'Permit fees'],
    addons: [
      { id: 'addon-5', title: 'Extended Warranty', price: 75, description: '3-year coverage on repairs' },
    ],
  },
  {
    id: 'svc-4',
    slug: 'emergency-tarp',
    category: 'storm',
    title: 'Emergency Roof Tarp',
    description: '24/7 emergency service to protect your home from storm damage. Fast response guaranteed.',
    heroImage: emergencyTarpImg,
    basePrice: 400,
    unit: 'fixed',
    durationMin: 120,
    inclusions: ['Emergency response', 'Heavy-duty tarp', 'Professional installation', 'Temporary protection'],
    exclusions: ['Permanent repairs', 'Insurance claims processing', 'Interior cleanup'],
    addons: [
      { id: 'addon-6', title: 'After-Hours Service', price: 150, description: 'Evening/weekend priority response' },
    ],
  },
  {
    id: 'svc-5',
    slug: 'skylight-reseal',
    category: 'maintenance',
    title: 'Skylight Resealing',
    description: 'Stop leaks around skylights with professional resealing. Prevent water damage and improve energy efficiency.',
    heroImage: skylightResealImg,
    basePrice: 275,
    unit: 'fixed',
    durationMin: 150,
    inclusions: ['Old sealant removal', 'Professional-grade sealant', 'Frame inspection', '2-year warranty'],
    exclusions: ['Skylight replacement', 'Frame repair', 'Interior painting'],
    addons: [],
  },
  {
    id: 'svc-6',
    slug: 'gutter-guards',
    category: 'gutters',
    title: 'Gutter Guard Installation',
    description: 'Premium gutter protection system. Reduce maintenance and extend gutter life.',
    heroImage: gutterGuardsImg,
    basePrice: 12,
    unit: 'linear_ft',
    durationMin: 240,
    inclusions: ['Premium mesh guards', 'Professional installation', 'Gutter cleaning before install', '5-year warranty'],
    exclusions: ['Gutter replacement', 'Fascia repair', 'Downspout extensions'],
    addons: [
      { id: 'addon-7', title: 'Heated Gutter System', price: 500, description: 'Prevent ice dams and clogs' },
    ],
  },
  {
    id: 'svc-7',
    slug: 'roof-tune-up',
    category: 'maintenance',
    title: 'Roof Tune-Up',
    description: 'Annual maintenance package. Keep your roof in top condition and catch issues early.',
    heroImage: roofTuneupImg,
    basePrice: 225,
    unit: 'fixed',
    durationMin: 120,
    inclusions: ['Complete inspection', 'Minor repairs', 'Sealant touch-up', 'Gutter check', 'Photo report'],
    exclusions: ['Major repairs', 'Material replacement', 'Structural work'],
    addons: [],
  },
  {
    id: 'svc-8',
    slug: 'chimney-flashing',
    category: 'roofing',
    title: 'Chimney Flashing Repair',
    description: 'Fix or replace chimney flashing to prevent leaks. Common source of water damage.',
    heroImage: chimneyFlashingImg,
    basePrice: 425,
    unit: 'fixed',
    durationMin: 180,
    inclusions: ['Old flashing removal', 'New metal flashing', 'Professional sealing', '2-year warranty'],
    exclusions: ['Chimney repair', 'Masonry work', 'Cap replacement'],
    addons: [],
  },
  {
    id: 'svc-9',
    slug: 'ventilation-upgrade',
    category: 'maintenance',
    title: 'Roof Ventilation Upgrade',
    description: 'Improve attic ventilation for better energy efficiency and roof longevity.',
    heroImage: ventilationImg,
    basePrice: 550,
    unit: 'fixed',
    durationMin: 240,
    inclusions: ['Ventilation assessment', 'Vent installation', 'Attic inspection', 'Energy efficiency report'],
    exclusions: ['Insulation work', 'Attic cleanup', 'Structural modifications'],
    addons: [
      { id: 'addon-8', title: 'Solar Attic Fan', price: 300, description: 'Energy-efficient ventilation' },
    ],
  },
  {
    id: 'svc-10',
    slug: 'downspout-extension',
    category: 'gutters',
    title: 'Downspout Extensions',
    description: 'Direct water away from foundation. Prevent basement flooding and foundation damage.',
    heroImage: downspoutExtensionImg,
    basePrice: 85,
    unit: 'linear_ft',
    durationMin: 90,
    inclusions: ['Extension pipe', 'Professional installation', 'Splash block', 'Grading assessment'],
    exclusions: ['Landscaping', 'French drains', 'Foundation waterproofing'],
    addons: [],
  },
];

export const demoUsers: User[] = [
  {
    id: 'user-1',
    name: 'Guest User',
    email: 'guest@example.com',
    phone: '',
    addresses: [],
    referralCode: 'GUEST123',
    credits: 0,
    tier: 'guest',
  },
  {
    id: 'user-2',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    phone: '(214) 555-0123',
    addresses: [
      {
        id: 'addr-1',
        label: 'Home',
        street: '1234 Oak Street',
        unit: '',
        city: 'Dallas',
        state: 'TX',
        zip: '75201',
        isDefault: true,
      },
      {
        id: 'addr-2',
        label: 'Rental Property',
        street: '5678 Elm Avenue',
        unit: 'Unit 2B',
        city: 'Fort Worth',
        state: 'TX',
        zip: '76102',
        isDefault: false,
      },
    ],
    referralCode: 'SARAH2024',
    credits: 25,
    tier: 'regular',
  },
  {
    id: 'user-3',
    name: 'Michael Chen',
    email: 'michael.chen@example.com',
    phone: '(817) 555-0456',
    addresses: [
      {
        id: 'addr-3',
        label: 'Home',
        street: '9012 Pine Lane',
        city: 'Arlington',
        state: 'TX',
        zip: '76015',
        isDefault: true,
      },
    ],
    referralCode: 'MIKE2024',
    credits: 150,
    tier: 'vip',
  },
];

export const demoOrders: Order[] = [
  {
    id: 'ord-1',
    userId: 'user-2',
    serviceId: 'svc-1',
    addonIds: ['addon-1'],
    addressId: 'addr-1',
    photos: [],
    preferredWindow: 'Next Tuesday, 8am-12pm',
    notes: 'Please call before arriving. Dog in backyard.',
    estimateLow: 180,
    estimateHigh: 220,
    status: 'completed',
    createdAt: '2024-10-15T10:30:00Z',
    scheduledAt: '2024-10-20T08:00:00Z',
    completedAt: '2024-10-20T10:45:00Z',
    quantity: 150,
  },
  {
    id: 'ord-2',
    userId: 'user-2',
    serviceId: 'svc-7',
    addonIds: [],
    addressId: 'addr-1',
    photos: [],
    preferredWindow: 'ASAP',
    notes: '',
    estimateLow: 225,
    estimateHigh: 225,
    status: 'scheduled',
    createdAt: '2024-11-01T14:20:00Z',
    scheduledAt: '2024-11-08T09:00:00Z',
  },
  {
    id: 'ord-3',
    userId: 'user-3',
    serviceId: 'svc-3',
    addonIds: ['addon-5'],
    addressId: 'addr-3',
    photos: [],
    preferredWindow: 'This week, any day',
    notes: 'Small leak above living room. Photos attached.',
    estimateLow: 400,
    estimateHigh: 475,
    status: 'on-site',
    createdAt: '2024-11-03T09:15:00Z',
    scheduledAt: '2024-11-05T13:00:00Z',
    quantity: 15,
  },
  {
    id: 'ord-4',
    userId: 'user-3',
    serviceId: 'svc-2',
    addonIds: ['addon-3'],
    addressId: 'addr-3',
    photos: [],
    preferredWindow: 'November 12, morning',
    notes: 'Annual inspection',
    estimateLow: 300,
    estimateHigh: 300,
    status: 'received',
    createdAt: '2024-11-04T16:45:00Z',
  },
];

export const demoPromos: Promo[] = [
  {
    id: 'promo-1',
    code: 'FALL2024',
    title: 'Fall Gutter Special',
    description: '15% off gutter cleaning and guard installation',
    discount: 0.15,
    active: true,
  },
  {
    id: 'promo-2',
    code: 'FIRST50',
    title: 'New Customer Discount',
    description: '$50 off your first service',
    discount: 50,
    active: true,
  },
  {
    id: 'promo-3',
    code: 'REFER25',
    title: 'Referral Reward',
    description: '$25 credit for each referral',
    discount: 25,
    active: true,
  },
];

export const demoNotifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'Service Scheduled',
    message: 'Your roof tune-up is scheduled for November 8 at 9:00 AM',
    timestamp: '2024-11-01T14:25:00Z',
    read: false,
    orderId: 'ord-2',
    type: 'order',
  },
  {
    id: 'notif-2',
    title: 'Technician En Route',
    message: 'John is on his way! ETA: 15 minutes',
    timestamp: '2024-11-05T12:45:00Z',
    read: false,
    orderId: 'ord-3',
    type: 'order',
  },
  {
    id: 'notif-3',
    title: 'Fall Special Available',
    message: 'Save 15% on gutter services with code FALL2024',
    timestamp: '2024-11-01T08:00:00Z',
    read: true,
    type: 'promo',
  },
  {
    id: 'notif-4',
    title: 'Service Completed',
    message: 'Your gutter cleaning is complete. Please leave us a review!',
    timestamp: '2024-10-20T10:50:00Z',
    read: true,
    orderId: 'ord-1',
    type: 'order',
  },
];
